import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const LaNord = localFont({
  src: [
    {
      path: "../../public/assets/fonts/LaNord-Light.woff",
      weight: "300",
      style: "normal"
    },
    {
      path: "../../public/assets/fonts/LaNord-Regular.woff",
      weight: "400",
      style: "normal"
    },
    {
      path: "../../public/assets/fonts/LaNord-Bold.woff",
      weight: "700",
      style: "normal"
    }

  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={LaNord.className}>
      <body
        className={"antialiased flex"}
      >
        {children}
      </body>
    </html>
  );
}
